version: '3'

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=queue_db
      - MYSQL_USER=queue
      - MYSQL_PASSWORD=queue
    volumes:
      - ./init.db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
volumes:
    db:
      name: queue_db_volume